export enum SalesOrgEmailsEnum {
  'AT' = 'info-at@distrelec.com',
  'BE' = 'sales.be@distrelec.com',
  'CH' = 'info@distrelec.com',
  'CZ' = 'info.cz@distrelec.com',
  'DE' = 'verkauf@distrelec.de',
  'DK' = 'danmark@elfadistrelec.com',
  'EE' = 'eesti@elfadistrelec.com',
  'EX' = 'export@distrelec.com',
  'FI' = 'myynti@elfadistrelec.com',
  'FR' = 'info.fr@distrelec.com',
  'HU' = 'info.hu@distrelec.com',
  'IT' = 'vendite.it@distrelec.com',
  'LT' = 'lietuva@elfadistrelec.com',
  'LV' = 'latvija@elfadistrelec.com',
  'NL' = 'sales.nl@distrelec.com',
  'NO' = 'norge@elfadistrelec.com',
  'PL' = 'obsluga.klienta@elfadistrelec.com',
  'RO' = 'info.ro@distrelec.com',
  'SE' = 'order@elfa.se',
  'SK' = 'info.sk@distrelec.com',
}
