INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistCarpetContentTeaser', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distcarpetcontentteaser', 'props', 20087, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistCarpetContentTeaserWithText', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distcarpetcontentteawite', 'props', 20088, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistCarpetItem', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distcarpetitem', 'props', 20089, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistCustomerErrorFeedback', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'customererrorfeedback', 'props', 26073, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistErpPriceConditionType', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'erppriceconditiontype', 'props', 20064, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistExtCarpetItem', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distextcarpetitem', 'props', 20092, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistExtHeroRotatingTeaser', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distextherorotatingtease', 'props', 20093, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistExtHeroRotatingTeaserItem', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distextherorotatingteait', 'props', 20094, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistHeroRotatingTeaser', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distherorotatingteaser', 'props', 20095, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistHeroRotatingTeaserItem', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distherorotatingteaserit', 'props', 20096, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistHeroRotatingTeaserWithText', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distherorotatingteaswite', 'props', 20097, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistRmaRequestProcessEntry', 'de.hybris.platform.persistence', 'distrelecB2Bcore', 'de.hybris.platform.persistence.GenericItem', 'distrmarequestprocessent', 'props', 20065, 2, 'DEFAULT');

INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_BaseStore2RegCountryRel', 'de.hybris.platform.persistence.link', 'distrelecB2Bcore', 'de.hybris.platform.persistence.link.Link', 'basestore2regcountryrel', 'props', 20053, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistDownloadMedia2Language', 'de.hybris.platform.persistence.link', 'distrelecB2Bcore', 'de.hybris.platform.persistence.link.Link', 'distdome2lang', 'props', 20063, 2, 'DEFAULT');
INSERT INTO YDeployments (Name, PackageName, ExtensionName, SuperName, TableName, PropsTableName, Typecode, Modifiers, TypeSystemName) VALUES ('distrelecB2Bcore_DistVideoMedia2Language', 'de.hybris.platform.persistence.link', 'distrelecB2Bcore', 'de.hybris.platform.persistence.link.Link', 'distvime2lang', 'props', 20066, 2, 'DEFAULT');
