import de.hybris.platform.acceleratorservices.setup.SetupImpexService;
import com.namics.hybris.toolbox.spring.SpringUtil;


SetupImpexService impexService = SpringUtil.getBean("setupImpexService", SetupImpexService.class);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/email-content.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/email-content_en.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/email-content_nl.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/email-content_fr.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/cms-navigation_en.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/cms-navigation_nl.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/cms-navigation_fr.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/cms-navigation-links.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/email-content.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/email-content_en.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/email-content_tr.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/cms-navigation_en.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/cms-navigation_tr.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/cms-navigation-links.impex", false, false);

return "Done!"