

import de.hybris.platform.acceleratorservices.setup.SetupImpexService;
import com.namics.hybris.toolbox.spring.SpringUtil;


SetupImpexService impexService = SpringUtil.getBean("setupImpexService", SetupImpexService.class);

// TODO This is an example, you should add here the file that you want to import
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ATContentCatalog/webtrekk.impex", false, false);


return "Done!"
