
import de.hybris.platform.commerceservices.setup.SetupImpexService;
import com.namics.hybris.toolbox.spring.SpringUtil;


SetupImpexService impexService = SpringUtil.getBean("setupImpexService", SetupImpexService.class);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ATContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ATContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_CHContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_CHContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_DEContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_DEContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ITContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ITContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_LTContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_LTContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_CZContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_CZContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_HUContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_HUContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ROContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ROContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_SKContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_SKContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_SEContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_SEContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_NOContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_NOContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_NLContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_NLContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_PLContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_PLContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_EEContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_EEContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_FIContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_FIContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_DKContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_DKContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_EXContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_EXContentCatalog/cms-navigation-links.impex", false, false);


impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_LVContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_LVContentCatalog/cms-navigation-links.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/cms-navigation-links.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/cms-navigation.impex", false, false);
impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/cms-navigation-links.impex", false, false);

return "Done!"