import com.namics.hybris.toolbox.spring.SpringUtil;
import de.hybris.platform.cockpit.systemsetup.CockpitImportConfig;
import de.hybris.platform.core.initialization.SystemSetupContext;
import de.hybris.platform.core.initialization.SystemSetup.Type;
import de.hybris.platform.core.initialization.SystemSetup.Process;

print("start import");
SystemSetupContext context = new SystemSetupContext(null, Type.ESSENTIAL, Process.UPDATE, "distrelecB2Bcore");
SpringUtil.getBean("cockpitImportConfig", CockpitImportConfig.class).importCockpitConfig(context);
print("import done");