
import de.hybris.platform.commerceservices.setup.SetupImpexService;
import com.namics.hybris.toolbox.spring.SpringUtil;


SetupImpexService impexService = SpringUtil.getBean("setupImpexService", SetupImpexService.class);

impexService.importImpexFile("/distrelecB2Bcore/import/base/common/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ATContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_CHContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_DEContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ITContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_LTContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_CZContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_HUContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_ROContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_SKContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_SEContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_NOContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_NLContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_PLContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_EEContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_FIContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_DKContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_EXContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_LVContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_BEContentCatalog/email-content.impex", false, false);

impexService.importImpexFile("/distrelecB2Bcore/import/project/contentCatalogs/distrelec_TRContentCatalog/email-content.impex", false, false);

return "Done!"