import { Request } from 'express';
import { resolveApiUrl, resolveMediaUrl } from './utils';

export const CSP_OPTIONS = {
  useDefaults: false,
  reportOnly: true,
  directives: {
    defaultSrc: [
      "'self'",
      'localhost:*',
      '*.local:*',
      "'unsafe-eval'",
      "'unsafe-inline'",
      'distrelec-public.s3.eu-central-1.amazonaws.com',
      '*.bing.com',
      '*.cloudflare.com',
      '*.demdex.net',
      '*.emjcd.com',
      'smetrics.distrelec.ch',
      '*.distrelec.com',
      '*.dynamicyield.com',
      '*.ensighten.com',
      '*.pushengage.com',
      '*.optimizely.com',
      'connect.facebook.net',
      '*.facebook.com',
      '*.google.com',
      '*.google-analytics.com',
      '*.googleadservices.com',
      '*.googletagmanager.com',
      'static.hotjar.com',
      '*.pushengage.com',
      '*.rapidspike.com',
      '*.reevoo.com',
      '*.emjcd.com',
      '*.mczbf.com',
      '*.thesmilingpencils.com',
      '*.eraser.thesmilingpencils.com',
      '*.gstatic.com',
      '*.snapeda.com',
      '*.reevoo.com',
      '*.perfdrive.com',
      '*.doubleclick.net',
      '*.exponea.com',
      '*.thisgreencolumn.com',
    ],
    scriptSrc: [
      "'self'",
      "'unsafe-eval'",
      "'unsafe-inline'",
      '*.distrelec.com',
      '*.doubleclick.net:*',
      '*.googletagmanager.com',
      '*.googleoptimize.com',
      'www.google-analytics.com',
      '*.gstatic.com',
      '*.ensighten.com',
      '*.pushengage.com',
      '*.rapidspike.com',
      '*.optimizely.com',
      'www.google.com',
      '*.clarity.ms',
      'snap.licdn.com:*',
      '*.bing.com',
      '*.thesmilingpencils.com',
      '*.mczbf.com',
      '*.snapeda.com',
      '*.pushengage.com:*',
      '*.reevoo.com',
      'connect.facebook.net',
      '*.facebook.com',
      '*.optimizely.com',
      '*.perfdrive.com',
      '*.exponea.com',
      'cdn.mxpnl.com',
      '*.stackadapt.com',
      '*.thisgreencolumn.com',
    ],
    objectSrc: [
      "'self'",
      'localhost:*',
      '*.local:*',
      (req: Request) => `${req.hostname}`,
      (req: Request) => `${resolveApiUrl(req)}`,
    ],
    connectSrc: [
      "'self'",
      'localhost:*',
      '*.local:*',
      'api.feefo.com',
      '*.ensighten.com',
      '*.pushengage.com',
      '*.stackadapt.com',
      '*.optimizely.com',
      '*.reevoo.com',
      '*.clarity.ms',
      '*.google-analytics.com:*',
      '*.doubleclick.net:*',
      '*.distrelec.com',
      '*.bing.com',
      '*.thesmilingpencils.com',
      '*.mczbf.com',
      '*.optimizely.com',
      '*.perfdrive.com',
      '*.pushengage.com',
      '*.rapidspike.com',
      '*.exponea.com',
      '*.lucidworks.cloud',
      '*.snapeda.com',
      'snapeda.s3.amazonaws.com',
      '*.thisgreencolumn.com',
      (req: Request) => `${resolveApiUrl(req)}`,
    ],
    imgSrc: [
      "'self'",
      "'self' data:",
      'localhost:*',
      '*.local:*',
      '*.ensighten.com:*',
      '*.pushengage.com:*',
      '*.stackadapt.com:*',
      '*.optimizely.com:*',
      '*.google-analytics.com:*',
      '*.distrelec.com:*',
      '*.doubleclick.net:*',
      '*.google.co.uk',
      '*.google.ch',
      '*.googletagmanager.com',
      '*.google.co.in',
      '*.linkedin.com:*',
      '*.snapeda.com',
      'snapeda.s3.amazonaws.com',
      '*.thesmilingpencils.com',
      '*.reevoo.com',
      'connect.facebook.net',
      '*.facebook.com',
      '*.perfdrive.com',
      '*.thisgreencolumn.com',
      (req: Request) => `${resolveMediaUrl(req)}`,
    ],
    styleSrc: ['*', "'unsafe-eval'", "'unsafe-inline'"],
    fontSrc: ["'self'", '*.reevoo.com', '*.gstatic.com'],
    frameSrc: [
      "'self'",
      '*.google.com',
      '*.youtube.com',
      '*.doubleclick.net',
      'spg.evopayments.eu',
      '*.facebook.com',
      '*.optimizely.com',
      '*.thisgreencolumn.com',
    ],
    reportUri: [(req: Request) => `${resolveApiUrl(req)}/rest/v2/report/csp-report`],
    upgradeInsecureRequests: [],
  },
};
